name: Gradle update

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.repository == 'Maxr1998/ModernAndroidPreferences'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          repo-token: ${{ secrets.GRADLE_UPDATE_TOKEN }}
